// Generate base64 blur placeholders for the real BWT assets used on the site.
// Run from project root:  node scripts/gen_blurs.mjs
// (Does NOT modify the source images — only reads them to build tiny blur previews.)
import sharp from "sharp";
import fs from "fs";
import path from "path";

const PUB = path.join("public", "images");

// key → image path (relative to public/images). Keys are referenced via imageBlurs.<key>.
const SRCS = {
  heroWater: "hero/water-splash-hero.jpg", // Section 1 hero background (cropped, no "References" text)
  limescale: "pain_points/limescale-kettle-interior.jpg", // S2 HiddenThreat, S3 Техника, S6 Техника
  slim: "products/bwt-slim-3-cartridges.jpg", // S4 SlimReveal, S7 popular card
  morning: "lifestyle/woman-drinking-water-morning.jpg", // S6 Утро
  guests: "hero/kitchen-faucet-glass-pour.jpg", // S6 Гости (Чай и кофе)
  cooking: "lifestyle/glass-with-ice-water.jpg", // S6 Готовка
  kids: "lifestyle/kids-drinking-water.jpg", // S3 Кожа детей, S6 Дети
  calm: "lifestyle/lab-scientist-water-sample.jpg", // S6 Спокойствие
  delivery: "installations/delivery-installation-team.jpg", // S8 service ecosystem
  installAbout: "installations/bwt-under-sink-install.jpg", // About page hero
  volosy: "pain_points/volosy.webp", // S3 Pain Points — hair
  vkus: "pain_points/vkus.webp", // S3 Pain Points — taste
  roditeli: "pain_points/roditeli.webp", // S3 Pain Points — family health
  vremya: "pain_points/vremya.webp", // S3 Pain Points — time & money
};

const blurs = {};
for (const [key, rel] of Object.entries(SRCS)) {
  const src = path.join(PUB, rel);
  const buf = await sharp(src).resize(20).webp({ quality: 45 }).toBuffer();
  blurs[key] = `data:image/webp;base64,${buf.toString("base64")}`;
  console.log(`${key.padEnd(13)} ← ${rel}`);
}

const ts =
  "// Auto-generated by scripts/gen_blurs.mjs — base64 blur placeholders for next/image.\n" +
  "export const imageBlurs = " +
  JSON.stringify(blurs, null, 2) +
  " as const;\n";
fs.writeFileSync(path.join("lib", "image-blurs.ts"), ts);
console.log("\nWrote lib/image-blurs.ts");
