// Optimize chosen source images → WebP into public/images/, generate blur placeholders.
// Run from project root:  node scripts/optimize_images.mjs
import sharp from "sharp";
import fs from "fs";
import path from "path";

const SRC = path.join("scripts", "source");
const PUB = path.join("public", "images");

// cropBottomPct: fraction of height to trim off the bottom (removes the Uzbek text strip).
const JOBS = [
  { src: "Artboard_4.png",  out: "hero/water.webp",         crop: 0.22, key: "heroWater" },
  { src: "Artboard_10.png", out: "products/bwt-slim.webp",  crop: 0.26, key: "slim" },
  { src: "Artboard_6.png",  out: "content/limescale.webp",  crop: 0.30, key: "limescale" },
  { src: "Artboard_8.png",  out: "lifestyle/morning.webp",  crop: 0.24, key: "morning" },
  { src: "Artboard_3.png",  out: "lifestyle/tap.webp",      crop: 0.28, key: "tap" },
  { src: "Artboard_7.png",  out: "lifestyle/lab.webp",      crop: 0.30, key: "lab" },
  { src: "Artboard_11.png", out: "lifestyle/delivery.webp", crop: 0.32, key: "delivery" },
];

const blurs = {};

for (const job of JOBS) {
  const srcPath = path.join(SRC, job.src);
  const outPath = path.join(PUB, job.out);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });

  const meta = await sharp(srcPath).metadata();
  let pipeline = sharp(srcPath);
  if (job.crop > 0) {
    const h = Math.round(meta.height * (1 - job.crop));
    pipeline = pipeline.extract({ left: 0, top: 0, width: meta.width, height: h });
  }
  await pipeline
    .resize({ width: 1600, withoutEnlargement: true })
    .webp({ quality: 82 })
    .toFile(outPath);

  // tiny blur placeholder
  const blurBuf = await sharp(srcPath).resize(16).webp({ quality: 40 }).toBuffer();
  blurs[job.key] = `data:image/webp;base64,${blurBuf.toString("base64")}`;

  const size = Math.round(fs.statSync(outPath).size / 1024);
  console.log(`${job.out}  (${size} KB)`);
}

const ts =
  "// Auto-generated by scripts/optimize_images.mjs — base64 blur placeholders for next/image.\n" +
  "export const imageBlurs = " +
  JSON.stringify(blurs, null, 2) +
  " as const;\n";
fs.writeFileSync(path.join("lib", "image-blurs.ts"), ts);
console.log("\nWrote lib/image-blurs.ts");
